### ISSUE TITLE
Column displaying server hostname/FQDN

### ISSUE THREAD

**Issue by crashykernel** [phpLicenseWatcher/phpLicenseWatcher#119]
Would it be possible to add a column to the status page that displays the hostname/FQDN of the Flexlm server that runs a license or service? In instances where multiple services are running off the same VM or physical server and cnames/aliases are used, it would be helpful if this information is available at a glance. This would help with quickly deciding if a network or other issue is the cause of multiple services being down, or if a single server is impacted.

**Comment by mcglow2** [comment]
Can you provide a screen shot or example of how you would envision the status page to look?  Please redact or mock up so that any confidential information is not included.  

I am open to adding additional labeling but want to make sure it is required, and their is not a way we can suggest to use the current fields available to configure and display the information you are looking for.

**Comment by crashykernel** [comment]
Thanks for your response. In the attached example, with multiple services and aliases running on each host, a hostname column makes it makes it easy to determine that there's something wrong with server2.

<img width="1110" alt="mockup" src="https://user-images.githubusercontent.com/103441986/163833979-572a89d2-5d7f-498e-a7f1-30736ccca8d1.png">

**Comment by mcglow2** [comment]
We do not plan to implement this at this time.
