### ISSUE TITLE
Document E-Mail sending

### ISSUE THREAD

**Issue by scs-kno** [phpLicenseWatcher/phpLicenseWatcher#157]
**Describe the bug**
Missing documentation on how to setup automatic e-mail warnings.
As in the old version.

**Expected behavior**
A clear and concise description of how to trigger emails.

http://server/license_alert.php?noemail=0 was the old way.

**Comment by pbailie** [comment]
For the moment — I believe the short version is to schedule Cron to run `license_alert.php`.

If you need help setting up scheduling parameters in Cron, this site is really helpful...
https://crontab.guru/

**Comment by scs-kno** [comment]
Maybe the problem is completely elsewhere:
> Fatal error: Uncaught mysqli_sql_exception: Unknown column 'lm_default_usage_reporting' in 'field list' in /var/www/html/common.php:153 Stack trace: #0 /var/www/html/common.php(153): mysqli->query('SELECT `name`, ...', 0) #1 /var/www/html/license_util.php(7): db_get_servers(Object(mysqli), Array) #2 {main} thrown in /var/www/html/common.php on line 153

Is there an update I missed?

**Comment by pbailie** [comment]
> Maybe the problem is completely elsewhere:
> 
> > Fatal error: Uncaught mysqli_sql_exception: Unknown column 'lm_default_usage_reporting' in 'field list' in /var/www/html/common.php:153 Stack trace: #0 /var/www/html/common.php(153): mysqli->query('SELECT `name`, ...', 0) #1 /var/www/html/license_util.php(7): db_get_servers(Object(mysqli), Array) #2 {main} thrown in /var/www/html/common.php on line 153
> 
> Is there an update I missed?

There is a database migration patch available to correct that at `database/migrations/migration-02.sql`.

Or just run this line in the database:
https://github.com/phpLicenseWatcher/phpLicenseWatcher/blob/80659cc1a97e97794397ec14b805bcbd63e92939/database/migrations/migration-02.sql#L3

**Comment by scs-kno** [comment]
Further digging reveals the following headers are sent even when running `wget -O - http://localhost/license_alert.php` from the command line:

```
    [0] => HTTP_USER_AGENT
    [1] => HTTP_ACCEPT
    [2] => HTTP_ACCEPT_ENCODING
    [3] => HTTP_HOST
    [4] => HTTP_CONNECTION
```

I think that explains the missing emails for now:

```php
if (empty(preg_grep("/^HTTP_/", array_keys($_SERVER)))) {
```

**Comment by pbailie** [comment]
The mentioned `preg_grep()` check is to determine if the page was accessed by CLI or by HTTP.  This could normally be done with `php_sapi_name()`, but a misconfiguration of PHP could incorrectly report HTTP.  So, I check for the existence of actual HTTP headers to make that determination.

When the file is accessed via HTTP, it is assumed the webpage view is being requested, so output is sent back as HTML text.  When the file is accessed by CLI, through PHP's runtime rather than HTTP, then it will send an email.  

By using `wget`, you get HTTP headers, so no email output.

Try scheduling cron to run `php path/to/license_alert.php`, instead of as a URL via `wget`.  

This is shown in step 5 of installation in the main readme.
